/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int ABSTRACT = 7;
  int BOOLEAN = 8;
  int CHAR = 9;
  int CLASS = 10;
  int DOUBLE = 11;
  int ELSE = 12;
  int EXTENDS = 13;
  int FOR = 14;
  int FALSE = 15;
  int IF = 16;
  int IMPORT = 17;
  int IMPLEMENTS = 18;
  int INTERFACE = 19;
  int INSTANCEOF = 20;
  int INT = 21;
  int NEW = 22;
  int NULL = 23;
  int PACKAGE = 24;
  int PRIVATE = 25;
  int PROTECTED = 26;
  int PUBLIC = 27;
  int RETURN = 28;
  int STATIC = 29;
  int SUPER = 30;
  int THIS = 31;
  int TRUE = 32;
  int VOID = 33;
  int WHILE = 34;
  int PLUS = 35;
  int ASSIGN = 36;
  int DEC = 37;
  int EQUAL = 38;
  int GT = 39;
  int INC = 40;
  int LAND = 41;
  int LE = 42;
  int LNOT = 43;
  int MINUS = 44;
  int PLUS_ASSIGN = 45;
  int STAR = 46;
  int LPAREN = 47;
  int RPAREN = 48;
  int LCURLY = 49;
  int RCURLY = 50;
  int LBRACK = 51;
  int RBRACK = 52;
  int SEMI = 53;
  int COMMA = 54;
  int DOT = 55;
  int IDENTIFIER = 56;
  int LETTER = 57;
  int DIGIT = 58;
  int NON_ZERO_DIGIT = 59;
  int EXPONENT = 60;
  int SIGN = 61;
  int SUFFIX = 62;
  int INT_LITERAL = 63;
  int DOUBLE_LITERAL = 64;
  int CHAR_LITERAL = 65;
  int STRING_LITERAL = 66;
  int ESC = 67;
  int ERROR = 68;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"char\"",
    "\"class\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"false\"",
    "\"if\"",
    "\"import\"",
    "\"implements\"",
    "\"interface\"",
    "\"instanceof\"",
    "\"int\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"<=\"",
    "\"!\"",
    "\"-\"",
    "\"+=\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<EXPONENT>",
    "<SIGN>",
    "<SUFFIX>",
    "<INT_LITERAL>",
    "<DOUBLE_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
